#!/usr/bin/env bash
# rebuilt home manager

bspc rule -a \* -o state=floating && xterm -e bash -c "nix-shell '<home-manager>' -A install; read -n 1 -p 'echo enter any key: '; bspc wm -r && pkill -USR1 -x sxhkd"
