#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
unset SSH_ASKPASS

killDaemons() {
    pkill sxhkd
    pkill dunst
    pkill $(pgrep discord)
    pkill polybar
}

# Environment
setEnv() {
    export PATH="${PATH}:$HOME/.config/scripts"
    # xrdb ~/.Xresources
    # . $HOME/.cache/wal/colors.sh
    sleep 0.1
}

# detect primary monitors and set
setMonitor() {
    MONITOR=$(xrandr | sed -n '2 p' | cut -d' ' -f1)
    RES=$(xrandr | sed -n '3 p' | cut -d' ' -f4)
    bspc monitor $MONITOR -d '|     1     ' \
                             '|     2     ' \
                             '|     3     ' \
                             '|     4     ' \
                             '|     5     ' \
                             '|     6     ' \
                             '|     7     ' \
                             '|     8     ' \
                             '|     9     ' \
                             '|     0     |'
    xrandr --output $MONITOR --mode $RES --scale 1x1 --rate 60
}

setBSPWMConfigs() {
    bspc config top_padding         0
    bspc config bottom_padding      0
    bspc config left_padding        0
    bspc config right_padding       0
    bspc config border_width        3
    bspc config window_gap          5

    bspc config borderless_monocle   true
    # bspc config gapless_monocle      true

    # bspc config normal_border_color $BLACK
    bspc config focused_border_color $WHITE
    bspc config split_ratio          0.5
    bspc config presel_border_color "#ffbec9"
    # bspc config border_radius        10
}

setBSPWMRules() {
    ## Winodw rules
    # remove all rules first
    bspc rule -r *:*
    bspc rule -a urxvt:float state=floating rectangle=500x800+200+50
    bspc rule -a vimiv state=floating rectangle=700x100+500+50
    bspc rule -a "lemonbar" layer=above
}

spawnDaemon() {
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
    $HOME/.config/polybar/start.sh &
    xinput set-prop 11 295 1
    dunst \
        -1b "$WHITE" -1f "$BLACK" -1fr "$BLACK" \
        -nb "$WHITE" -nf "$BLACK" -nfr "$BLACK" \
        -cb "$WHITE" -cf "$BLACK" -cfr "$BLACK" &
    sleep 0.5
}


theme() {
    # blurwal -m 1 -b 4 -s 4 &
    # nohup ~/.config/scripts/bspwpm-workspace-preview &
    dunstify "Welcome Home! \(^w^)/"
    file1="$HOME/.config/bspwm/background/jWTBsU0.jpg"
    feh --bg-fill $file1
}

# Start of the script

killDaemons
setEnv
setMonitor
setBSPWMConfigs
setBSPWMRules
spawnDaemon
theme
xrdb $HOME/.Xresources
