#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1
unset SSH_ASKPASS

killDaemons() {
    pkill sxhkd
    pkill dunst
    pkill picom
    pkill $(pgrep discord)
    pkill polybar
    pkill -f bspwpm-workspace-preview
}

# Environment
setEnv() {
    export PATH="${PATH}:$HOME/.config/scripts"
    # xrdb ~/.Xresources
    # . $HOME/.cache/wal/colors.sh
    sleep 0.1
}

# detect monitors and set
setMonitor() {
    bspc monitor DisplayPort-1  -d '|     壹     ' \
                                   '|     贰     ' \
                                   '|     叁     ' \
                                   '|     肆     ' \
                                   '|     伍     ' \
                                   '|     陆     ' \
                                   '|     柒     ' \
                                   '|     捌     ' \
                                   '|     玖     ' \
                                   '|     零     |'
    xrandr --output DisplayPort-1 --mode 3840x2160 --scale 0.9x0.9 --rate 60
}

setBSPWMConfigs() {
    bspc config top_padding         0
    bspc config bottom_padding      0
    bspc config left_padding        0
    bspc config right_padding       0
    bspc config border_width        3
    bspc config window_gap          5

    bspc config borderless_monocle   true
    # bspc config gapless_monocle      true

    # bspc config normal_border_color $BLACK
    bspc config focused_border_color $WHITE
    bspc config split_ratio          0.5
    bspc config presel_border_color "#ffbec9"
    # bspc config border_radius        10
}

setBSPWMRules() {
    ## Winodw rules
    # remove all rules first
    bspc rule -r *:*
    bspc rule -a urxvt:float state=floating rectangle=500x800+200+50
    bspc rule -a vimiv state=floating rectangle=700x100+500+50
    bspc rule -a "lemonbar" layer=above
}

spawnDaemon() {
    sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
    $HOME/.config/polybar/start.sh &
    xinput set-prop 11 295 1
    picom &
    dunst \
        -1b "$WHITE" -1f "$BLACK" -1fr "$BLACK" \
        -nb "$WHITE" -nf "$BLACK" -nfr "$BLACK" \
        -cb "$WHITE" -cf "$BLACK" -cfr "$BLACK" &
    sleep 0.5
}


theme() {
    # blurwal -m 1 -b 4 -s 4 &
    # nohup ~/.config/scripts/bspwpm-workspace-preview &
    dunstify "Welcome Home! \(^w^)/"
    file1="$HOME/.config/bspwm/background/girl-city-bg.jpg"
    feh --bg-fill $file1
}

# Start of the script

killDaemons
setEnv
setMonitor
setBSPWMConfigs
setBSPWMRules
spawnDaemon
theme
