#!/bin/sh

# prepare
pkill blurwal
pkill dunst
pkill ibus-daemon
pkill vanela
pkill compton
pkill -f bspwpm-workspace-preview

# Environment
export PATH="${PATH}:$HOME/.config/scripts"
xrdb ~/.Xresources

sleep 0.5

. $HOME/.cache/wal/colors.sh
FOREGROUND=$foreground
BACKGROUND=$background
BLACK=$color0
RED=$color1
GREEN=$color2
YELLOW=$color3
BLUE=$color4
MAGENTA=$color5
CYAN=$color6
WHITE=$color7

bspc monitor eDP-1 -d '5' '6' '7' '8'
bspc monitor DP-2 -d  '1' '2' '3' '4'
bspc config top_padding         -5
bspc config bottom_padding      15
bspc config left_padding        0
bspc config right_padding       0
bspc config border_width        5
bspc config window_gap          10

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config normal_border_color $BLACK
bspc config focused_border_color $WHITE
bspc config presel_border_color "#ffbec9"
bspc config split_ratio          0.5
bspc config border_radius        10

## Winodw rules
# remove all rules first
bspc rule -r *:*
bspc rule -a urxvt:float state=floating rectangle=500x800+200+50
bspc rule -a vimiv state=floating rectangle=700x100+500+50
bspc rule -a "lemonbar" layer=above

ibus-daemon -drx

# secondary monitor
xrandr --output eDP-1 --rate 120 -mode 1920x1080

# primary monitor
xrandr --output DP-2 --left-of eDP-1

# rotate
# xrandr --output DP-2 --rotate right --left-of eDP-1
sxhkd -c  ~/.config/sxhkd/sxhkdrc &
vanela &
mpc update
mpc listall | mpc add
compton --config ~/.config/compton-blur-term.conf&
xinput set-prop 11 295 1
dunst \
    -1b "$WHITE" -1f "$BLACK" -1fr "$BLACK" \
    -nb "$WHITE" -nf "$BLACK" -nfr "$BLACK" \
    -cb "$WHITE" -cf "$BLACK" -cfr "$BLACK" &
sleep 0.5
blurwal -m 1 -b 4 -s 4 &
notify-send "Welcome Home! \(^w^)/"
nohup ~/.config/scripts/bspwpm-workspace-preview &
wal --themed solarized -l
feh --bg-max ~/.config/scripts/static/images/dune.jpg
# wal -qi ~/img/pokebeach.jpg -l --saturate 0.4 -b "#1c1a1a"> /dev/null
