#!/usr/bin/env python
"""
Convert xls to python
"""

import getopt
import sys
import os
import pandas as pd

try:
    # Short option syntax: "hv:"
    # Long option syntax: "help" or "verbose="
    opts, args = getopt.getopt(sys.argv[1:], "hvf:", ["help", "verbose", "file"])

except getopt.GetoptError as err:
    print(err)

for option, argument in opts:
    if option in ("-h", "--help"):
        print("Usage xlsjon -[hv] -f <file>")

    elif option in ("-v", "--verbose"):
        verbose = argument

    elif option in ("-f", "--file"):
        xls = pd.ExcelFile(argument, sheet_name=None)
        dfs = {sn: xls.parse(sn) for sn in xls.sheet_names}
            print(dfs[xls.sheet_names[1]].to_json(orient='records'))
