#!/bin/bash

export _JAVA_AWT_WM_NONREPARENTING=1
unset SSH_ASKPASS
source "$HOME/.config/bspwm/configs.sh"

kill_daemons() {
    pkill sxhkd
    pkill dunst
    pkill compton
}

init_daemons() {
    init_sxhkd
    init_polybar
    init_dunst
    compton &
}

setup_monitors() {
    MONITOR=$(xrandr | sed -n '2 p' | cut -d' ' -f1)
    RES=$(xrandr | sed -n '3 p' | cut -d' ' -f4)
    bspc monitor $MONITOR -d '壹' '贰' '叁' '肆' '伍'
    xrandr --output $MONITOR --mode $RES --scale 1x1 --rate 60
}

kill_daemons
setup_paths
setup_monitors
bspwm_configs
bspwm_rules
init_daemons
background

# machine specific setups
xrdb $HOME/.Xresources
