{
  imports = [
    ./alacritty/default.nix
    ./bspwm/default.nix
    ./compton/default.nix
    ./dunst/default.nix
    ./emacs/default.nix
    ./fish/default.nix
    ./git/default.nix
    ./kitty/default.nix
    ./neovim/default.nix
    ./nmap/default.nix
    ./polybar/default.nix
    ./ranger/default.nix
    ./rofi/default.nix
    ./scripts/index.nix
    ./sxhkd/default.nix
    ./taskwarrior/default.nix
    ./tmux/default.nix
    ./zsh/default.nix
  ];
}
