#!/bin/bash

# A messy & pathetic script to launch rofi with xrdb colours
# Cheers! addy

. "$HOME/.cache/wal/colors.sh"

# getcolors () {
# 	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
# 	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
# 	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
# 	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
# 	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
# 	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
# 	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
# 	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
# 	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
# 	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
# }
# getcolors

FOREGROUND=$foreground
BACKGROUND=$background
BLACK=$color0
RED=$color1
GREEN=$color2
YELLOW=$color3
BLUE=$color4
MAGENTA=$color5
CYAN=$color6
WHITE=$color7


# Launch rofi with custom configuration
rofi -show $1 -sidebar-mode \
-modi ,drun,window,ssh \
-hide-scrollbar true \
-bw 10 \
-lines 20 \
-padding 80 \
-width 40 \
-location 2 \
-columns 1 \
-terminal urxvt \
-font " Iosevka,Iosevka Bold Extended:style=Bold Extended,Regular 14" \
-color-enabled true \
-color-window "$BACKGROUND,$WHITE,$BACKGROUND" \
-color-normal "$BACKGROUND,$FOREGROUND,$BACKGROUND,$BACKGROUND,$GREEN" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND,$BACKGROUND,$GREEN" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND,$BACKGROUND,$GREEN" \
-run-shell-command '{terminal} -e \\" {cmd}; read -n 1 -s"'

#-font "ProggyClean TT CE 20" \

# Theming help
# color window = background, border, separator
# color normal = background, foreground, background-alt, highlight-background, highlight-foreground
# color active = background, foreground, background-alt, highlight-background, highlight-foreground
# color urgent = background, foreground, background-alt, highlight-background, highlight-foreground
