#!/usr/bin/bash
#random number
ID=3421
case $1 in
    up)
        light -A 10
        dunstify -t 1000 -r $ID "Brightness: `light`"
        ;;
    down)
        light -U 10
        dunstify -t 1000 -r $ID "Brightness: `light`"
esac
