#!/usr/bin/bash

# Start up code for tmux

code_session () {
    tmux new-session -s CODE -d 'cd ~; zsh -i'
    tmux rename-window -t CODE "Main"
}

scrap_session () {
    tmux new-session -s MISC -d 'cd ~; zsh -i;'
    tmux new-window -t MISC:1 'cd ~/Pictures/screenshot; ranger;'
    tmux rename-window -t MISC :1 "screenshot"

    tmux new-window -t MISC:2 'cd ~; ranger;'
    tmux rename-window -t MISC:2 "file manager"
}

note_session() {
    tmux new-session -s NOTE -d 'cd ~/Repo; zsh -i'
    tmux new-window -t NOTE:1 'cd ~/vimwiki; zsh -i'
    tmux rename-window -t NOTE:1 "my wiki"
}

work_session() {
    tmux new-session -s TASK -d 'cd ~; zsh -i'
}

monitor_session () {
    tmux new-session -s MONITOR -d 'task cale; while sleep 10; do clear; task cale; done'
    tmux split-window -v 'task; while sleep 10; do clear; task; done'
    tmux split-window -h 'zsh -i'
}

note_session
work_session
code_session
scrap_session
monitor_session

tmux attach-session -d -t NOTE
