#!/usr/bin/env bash
CURRENT_ENGINE=$(ibus engine)
EN_ENGINE=$(ibus list-engine | grep -i xkb:us::eng)
CN_ENGINE=$(ibus list-engine | grep -i libpinyin)
# JP_ENGINE=$(ibus list-engine | grep -i Anthy)
MSG="ibus: "
EN="EN us"
CN="CN libpinyin"
JP="JP Anthy"
# randome number
ID=2593

if [[ $1 == "FORCE" ]]; then
    dunstify -t 1000 -r $ID "Force swiching ibus to English"
    ibus engine xkb:us::eng
    exit
fi

change_and_send() {
   ibus engine $1
   dunstify -t 1000 -r $ID $2
}

if [[ $EN_ENGINE =~ $CURRENT_ENGINE ]]; then
    change_and_send "$CN_ENGINE" "$MSG $CN"

# elif [[ $CN_ENGINE =~ $CURRENT_ENGINE ]]; then
#     change_and_send "$JP_ENGINE" "$MSG $JP"

elif [[ $JP_ENGINE =~ $CURRENT_ENGINE ]]; then
    change_and_send "$EN_ENGINE" "$MSG $EN"

else
    change_and_send "$EN_ENGINE" "$MSG $EN"
fi
