#!/usr/bin/bash
ID=2319

getvol(){
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

ismute(){
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > dev/null
}

case $1 in
    up)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse sset Master 5%+ > /dev/null
        dunstify -t 1000 -r $ID "Volume: `getvol`"
        ;;
    down)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse sset Master 5%- > /dev/null
        dunstify -t 1000 -r $ID "Volume: `getvol`"
        ;;
    mute)
        amixer -D pulse set Master 1+ toggle > /dev/null
        if ismute; then
            dunstify -t 1000 -r $ID "Volume: muted"
        else
            dunstify -t 1000 -r $ID "Volume: `getvol`"
        fi
esac
